version: '3'
services:
#mssql docker
  carservice-sql:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=QWElkj132!
      - MSSQL_PID=Developer
    ports:
      - 1401:1433
    networks:
      - carservicenet

  carservice-api:
    restart: unless-stopped
    build:
      context: .
    environment:
      - ConnectionStrings:localDB=Server=carservice-sql,1433;Database=170170;User=sa;Password=QWElkj132!;ConnectRetryCount=0
    ports:
      - 58065:80
    networks:
      - carservicenet
    links:
      - carservice-sql
    depends_on:
      - carservice-sql

networks:
  carservicenet:
    driver: bridge       